apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-1.fullname" . }}
  labels:
    app: ngnix
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "application-1.selectorLabels" . | nindent 4 }}
